### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xNightswitch** [ReaperAnon/Shadow-Of-War-Mods#1]
Will you add an open source license so these mods and the dll loader can be reuploaded on Nexus Mods?

**Comment by ReaperAnon** [comment]
No, I don't want my things on the nexus because I don't like how the site is being run.

I'm working on remaking them in MSVC right now and I added a logging and mod config menu API to the mod loader as well, for the zero people other than myself who use it. lol

Once I'm finished I'll upload the source files here under one VS project and the actual mods in individual packages in the releases section.

![image](https://github.com/ReaperAnon/Shadow-Of-War-Mods/assets/63963239/3a4acb56-80af-4b9e-9a67-05064524d79f)

**Comment by ReaperAnon** [comment]
That's good to hear. Maybe someone else can make some higher effort things than me, I don't particularly enjoy reversing stuff.
